definitions:
  dbmodel.TeamEntry:
    properties:
      color:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      idgame:
        type: string
      idteam:
        type: string
      name:
        type: string
      score:
        type: integer
      updated_at:
        type: string
    type: object
  model.BombRequest:
    properties:
      id_user:
        type: string
      lat:
        type: number
      long:
        type: number
      type_bomb:
        type: string
    required:
    - id_user
    - lat
    - long
    - type_bomb
    type: object
  model.BombResponse:
    properties:
      bomb_id:
        type: integer
      id_user:
        type: string
      lat:
        type: number
      long:
        type: number
      type_bomb:
        type: string
    type: object
  model.BombUpdateRequest:
    properties:
      lat:
        type: number
      long:
        type: number
      type_bomb:
        type: string
    type: object
  model.GameRequest:
    properties:
      center_latitude:
        type: number
      center_longitude:
        type: number
      ending_date:
        type: string
      size:
        type: number
      starting_date:
        type: string
    type: object
  model.GameResponse:
    properties:
      center_latitude:
        type: number
      center_longitude:
        type: number
      ending_date:
        type: string
      size:
        type: number
      starting_date:
        type: string
      teams:
        items:
          $ref: '#/definitions/model.TeamResponse'
        type: array
    type: object
  model.TeamRequest:
    properties:
      color:
        type: string
      id_game:
        type: string
      name:
        type: string
      score:
        type: integer
    type: object
  model.TeamResponse:
    properties:
      color:
        type: string
      id_game:
        type: string
      name:
        type: string
      score:
        type: integer
    type: object
<<<<<<< HEAD
=======
  model.UserCreatePayload:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.UserLoginPayload:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:7774
>>>>>>> pre-release
info:
  contact: {}
  description: API pour le jeu BombParty
  title: BombParty API
  version: "1.0"
paths:
  /api/v1/bombs:
    get:
      consumes:
      - application/json
      description: Get all bombs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.BombResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List all bombs
      tags:
      - Bombs
    post:
      consumes:
      - application/json
      description: Create a new bomb with the provided data
      parameters:
      - description: Bomb data
        in: body
        name: bomb
        required: true
        schema:
          $ref: '#/definitions/model.BombRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.BombResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new bomb
      tags:
      - Bombs
  /api/v1/bombs/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a bomb by ID
      parameters:
      - description: Bomb ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete a bomb
      tags:
      - Bombs
    get:
      consumes:
      - application/json
      description: Get a single bomb by its ID
      parameters:
      - description: Bomb ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BombResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get a bomb by ID
      tags:
      - Bombs
    put:
      consumes:
      - application/json
      description: Update an existing bomb
      parameters:
      - description: Bomb ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bomb update data
        in: body
        name: bomb
        required: true
        schema:
          $ref: '#/definitions/model.BombUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BombResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update a bomb
      tags:
      - Bombs
  /api/v1/bombs/user/{userId}:
    get:
      consumes:
      - application/json
      description: Get all bombs created by a specific user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.BombResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List bombs by user
      tags:
      - Bombs
<<<<<<< HEAD
  /game:
=======
  /api/v1/game:
>>>>>>> pre-release
    post:
      consumes:
      - application/json
      description: Creates a new Game entry in the database
      parameters:
      - description: Game creation payload
        in: body
        name: Game
        required: true
        schema:
          $ref: '#/definitions/model.GameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GameResponse'
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to create Game
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new Game
      tags:
      - games
<<<<<<< HEAD
  /game/{id}:
=======
  /api/v1/game/{id}:
>>>>>>> pre-release
    get:
      description: Retrieves a specific game from the database by its ID, including
        associated teams
      parameters:
      - description: game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GameResponse'
        "404":
          description: Game not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to find specific game
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get game by ID
      tags:
      - games
<<<<<<< HEAD
  /games:
=======
  /api/v1/games:
>>>>>>> pre-release
    get:
      description: Retrieves a list of all games from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GameResponse'
            type: array
        "500":
          description: Failed to retrieve games
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all games
      tags:
      - games
<<<<<<< HEAD
  /games/{id}:
=======
  /api/v1/games/{id}:
>>>>>>> pre-release
    delete:
      description: Deletes a game from the database by its ID
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Game deleted successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Game not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to delete game
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete a game
      tags:
      - games
    patch:
      consumes:
      - application/json
      description: Updates an existing game's information in the database
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      - description: Game update payload
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/model.GameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GameResponse'
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Game not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to update game
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update a game
      tags:
      - games
<<<<<<< HEAD
  /teams:
=======
  /api/v1/teams:
>>>>>>> pre-release
    get:
      description: Retrieve all teams
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dbmodel.TeamEntry'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all teams
      tags:
      - Teams
    post:
      consumes:
      - application/json
      description: Create a new team linked to a game
      parameters:
      - description: Team payload
        in: body
        name: team
        required: true
        schema:
          $ref: '#/definitions/model.TeamRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dbmodel.TeamEntry'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a team
      tags:
      - Teams
<<<<<<< HEAD
  /teams/{id}:
=======
  /api/v1/teams/{id}:
>>>>>>> pre-release
    delete:
      description: Delete a team by ID
      parameters:
      - description: Team ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a team
      tags:
      - Teams
    get:
      description: Retrieve a team by its UUID
      parameters:
      - description: Team ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dbmodel.TeamEntry'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get team by ID
      tags:
      - Teams
    put:
      consumes:
      - application/json
      description: Update an existing team
      parameters:
      - description: Team ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Updated team payload
        in: body
        name: team
        required: true
        schema:
          $ref: '#/definitions/model.TeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dbmodel.TeamEntry'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a team
      tags:
      - Teams
<<<<<<< HEAD
=======
  /user/login:
    post:
      consumes:
      - application/json
      description: Authentifie un utilisateur avec son email et mot de passe et retourne
        un token JWT
      parameters:
      - description: Identifiants de connexion
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Token JWT généré
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erreur avec le payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Identifiants invalides
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erreur serveur
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Connexion utilisateur
      tags:
      - auth
  /user/register:
    post:
      consumes:
      - application/json
      description: Enregistre un nouvel utilisateur avec un nom d'utilisateur, email
        et mot de passe
      parameters:
      - description: Informations d'inscription
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserCreatePayload'
      produces:
      - application/json
      responses:
        "200":
          description: Token JWT généré
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erreur avec le payload
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erreur serveur
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Créer un nouveau compte utilisateur
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" suivi de votre token JWT
    in: header
    name: Authorization
    type: apiKey
>>>>>>> pre-release
swagger: "2.0"
